name: Fetch YouTube Videos

on:
  schedule:
    - cron: '0 1 * * *'   # Runs daily at 1am UTC
  workflow_dispatch:

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser

    - name: Fetch YouTube RSS and convert to Markdown
      run: |
        mkdir -p _posts/youtube
        python scripts/fetch_youtube.py

    - name: Commit and push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add _posts/youtube/
        git commit -m "Update YouTube videos" || echo "No changes to commit"
        git push origin HEAD:main
